services:
  crawler:
    build: .
    restart: unless-stopped
    volumes:
      # Bind mount for .env files
      # Update the left side to match your Docker VM's path
      - ./.env:/app/.env
    env_file:
      - .env
